# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: brentgruberorg
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: tasks
service: tasks-api

useDotenv: true

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'development'}
  region: ${opt:region, 'us-east-2'}
  logRetentionDays: 30
  environment:
    APP_ENVIRONMENT: ${self:provider.stage}

functions:
  API:
    handler: main.handler
    timeout: 10
    memorySize: 512
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: 
            origin: ${env:ALLOWED_ORIGINS}
            maxAge: 60

custom:
  pythonRequirements:
    usePoetry: true
    noDeploy:
      - boto3
      - botocore

plugins:
  - serverless-python-requirements